export const categories = [
    "Rent/Mortgage",
    "Groceries",
    "Public Transportation",
    "Fuel/Gas",
    "Car Maintenance",
    "Health Insurance",
    "Medical Bills",
    "Clothing",
    "Entertainment",
    "Internet Service",
    "Mobile Phone",
    "TV/Cable",
    "Education/Tuition",
    "Credit Card Payments",
    "Savings",
    "Gifts",
    "Pet Care",
    "Gym Membership",
    "Home Maintenance",
    "Vacation/Travel",
    "Books",
    "Office Supplies",
    "Legal Fees",
    "Accounting Fees",
    "Professional Development",
    "Haircuts/Salon",
    "Hobbies",
    "Electronics",
    "Furniture",
    "Home Decor",
    "Gardening",
    "Sports Activities",
    "Concerts/Events",
    "Parking Fees",
    "Tolls",
    "Postage/Shipping",
    "ATM Fees",
    "Charity/Donations",
    "Political Contributions",
    "Retirement Contributions",
    "Cloud Storage",
    "Online Courses"
  ];
  